<a href="https://colab.research.google.com/github/ralsouza/TensorFlow/blob/master/src/04_TensorFlow_Placeholders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Placeholders
Quando não temos os valores definidos previamente para os tensores, usamos os placeholders para reservar estes objetos antes de executar uma sessão. 

Uma sessão só pode ser aberta e ser executada se houver um tensor criado e então ao executar a operação devemos usar o comando `feed_dict`
para preencher os valores nos placeholders reservados.

Esta automação é interessante, pois assim podemos trazer dados de diversas fontes de dados para usar no fluxo de cálculos.

In [1]:
%tensorflow_version 1.x
import tensorflow as tf

TensorFlow 1.x selected.


In [4]:
# Criação dos grafos
a = tf.placeholder(tf.int32,shape=(3,1))
b = tf.placeholder(tf.int32,shape=(1,3))
c = tf.matmul(a,b)

# Executar grafo
with tf.Session() as sess:
  print(sess.run(c,feed_dict={a:[[3],[2],[1]],b:[[1,2,3]]}))

[[3 6 9]
 [2 4 6]
 [1 2 3]]
